### ISSUE TITLE
Add new team members to Org

### ISSUE THREAD

**Issue by itsme-hayden** [LHSPantherbots/.github#1]
During the meeting on Saturday 12/28/24, we had four team members create GitHub accounts wanting to join the organization; they are as follows:

+ Kiahley Vann - [KiahV ](https://github.com/KiahV)
+ Jairon Acosta - [Sn0w1y](https://github.com/Sn0w1y)
+ Nate Weiner - [Nate-Weiner1234](https://github.com/Nate-Weiner1234)
+ Matthew Hague - [MathewHague](https://github.com/MathewHague)

If they could be added to the organization and/or if I could be promoted to an owner role, that would be a great help. Thank you!

Hayden Futch

**Comment by chadr03** [comment]
Done
